# Generated by Django 4.2.7 on 2023-11-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpage',
            name='entry',
            field=models.TextField(null=True),
        ),
    ]
