# Generated by Django 4.2.7 on 2023-12-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0003_remove_journalpage_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
    ]
