# Generated by Django 4.2.7 on 2023-11-28 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0003_remove_journalpage_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.AddField(
            model_name='journalpage',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journaling.journal'),
        ),
    ]
