# Generated by Django 4.2.7 on 2023-12-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0004_remove_journal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journaling.journaltype'),
        ),
    ]
