# Generated by Django 4.2.7 on 2023-11-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0004_remove_journal_user_journalpage_journal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='date_completed',
            new_name='date_started',
        ),
        migrations.AddField(
            model_name='journal',
            name='date_last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
