# Generated by Django 4.2.7 on 2023-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0005_journaltype_alter_journal_journal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='date_completed',
            new_name='date_started',
        ),
        migrations.AddField(
            model_name='journal',
            name='date_last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
