# Generated by Django 4.2.7 on 2023-12-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0006_rename_date_completed_journal_date_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpage',
            name='journal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journaling.journal'),
            preserve_default=False,
        ),
    ]
