# Generated by Django 4.2.7 on 2023-11-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0006_alter_journal_journal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journaling.journaltypes'),
        ),
    ]
