# Generated by Django 4.2.7 on 2023-11-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0007_journaltypes_alter_journal_journal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Empty Page', max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='name',
            field=models.CharField(default='Journal', max_length=50),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journaling.journaltype'),
        ),
        migrations.DeleteModel(
            name='JournalTypes',
        ),
    ]
