# Generated by Django 4.2.7 on 2023-12-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0007_journalpage_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
