# Generated by Django 4.2.7 on 2023-12-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=125)),
                ('good_habit', models.BooleanField(default=True)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
